# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      # use 15-MB stub so GH runner never pulls big checkpoints
      MODEL_ID: "sshleifer/tiny-gpt2"
      TRANSFORMERS_NO_ADVISORY_WARNINGS: "1"
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .                 # editable install so `import fracton` works
        pip install -r requirements.txt  # torch, transformers, …
        pip install flake8 pytest-cov

    - name: Lint with flake8
      run: flake8 fracton || true      # non-blocking for now

    - name: Test with pytest
      run: pytest --maxfail=1 --disable-warnings
